# Generated by Django 5.2.1 on 2025-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_duration_days',
            field=models.PositiveIntegerField(default=14, help_text='Duration of borrow period in days'),
        ),
        migrations.AddField(
            model_name='order',
            name='borrow_expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('borrowed', 'Borrowed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
