# Generated by Django 5.2.1 on 2025-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_borrow_duration_days_order_borrow_expiry_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_duration_days',
            field=models.PositiveIntegerField(help_text='Duration of borrow period in days'),
        ),
    ]
