# Generated by Django 5.2.1 on 2025-05-10 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_borrow_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duration of borrow period in days'),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='book_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('borrowed', 'Borrowed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
