# Generated by Django 5.2.1 on 2025-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_borrow_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='', help_text='A brief description of the book.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_duration_days',
            field=models.PositiveIntegerField(help_text='Duration of borrow period in days'),
        ),
    ]
