# Generated by Django 5.2.1 on 2025-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_description_alter_book_borrow_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrow_duration_days',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrow_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='borrow_expiry_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('purchase', 'Purchase')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
